/**
 * Mock file for turn_and_scoring_test.dart
 * Date: 2025-11-10
 * Function: Provides mock implementations for testing turn management and scoring services
 * Generated manually for Alpha Version 1 - Android device compatibility
 */

// Mocks generated by Mockito 5.4.2 from annotations
// in mind_wars/test/turn_and_scoring_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mind_wars/models/models.dart' as _i5;
import 'package:mind_wars/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:http/http.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

// ignore: unused_element
class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);
  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<Map<String, dynamic>> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<List<_i5.GameLobby>> getLobbies() => (super.noSuchMethod(
        Invocation.method(
          #getLobbies,
          [],
        ),
        returnValue: _i4.Future<List<_i5.GameLobby>>.value(<_i5.GameLobby>[]),
      ) as _i4.Future<List<_i5.GameLobby>>);
  @override
  _i4.Future<_i5.GameLobby> createLobby(
    String? name,
    int? maxPlayers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLobby,
          [
            name,
            maxPlayers,
          ],
        ),
        returnValue: _i4.Future<_i5.GameLobby>.value(_FakeGameLobby_1(
          this,
          Invocation.method(
            #createLobby,
            [
              name,
              maxPlayers,
            ],
          ),
        )),
      ) as _i4.Future<_i5.GameLobby>);
  @override
  _i4.Future<_i5.GameLobby> getLobby(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #getLobby,
          [lobbyId],
        ),
        returnValue: _i4.Future<_i5.GameLobby>.value(_FakeGameLobby_1(
          this,
          Invocation.method(
            #getLobby,
            [lobbyId],
          ),
        )),
      ) as _i4.Future<_i5.GameLobby>);
  @override
  _i4.Future<List<Map<String, dynamic>>> getGames() => (super.noSuchMethod(
        Invocation.method(
          #getGames,
          [],
        ),
        returnValue:
            _i4.Future<List<Map<String, dynamic>>>.value(<Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
  @override
  _i4.Future<Map<String, dynamic>> submitGameResult(
    String? gameId,
    String? lobbyId,
    Map<String, dynamic>? gameData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitGameResult,
          [
            gameId,
            lobbyId,
            gameData,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> validateMove(
    String? gameId,
    Map<String, dynamic>? moveData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateMove,
          [
            gameId,
            moveData,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<List<_i5.LeaderboardEntry>> getWeeklyLeaderboard() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyLeaderboard,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.LeaderboardEntry>>.value(<_i5.LeaderboardEntry>[]),
      ) as _i4.Future<List<_i5.LeaderboardEntry>>);
  @override
  _i4.Future<List<_i5.LeaderboardEntry>> getAllTimeLeaderboard() => (super.noSuchMethod(
        Invocation.method(
          #getAllTimeLeaderboard,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.LeaderboardEntry>>.value(<_i5.LeaderboardEntry>[]),
      ) as _i4.Future<List<_i5.LeaderboardEntry>>);
  @override
  _i4.Future<Map<String, dynamic>> getUserProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> updateUserProfile(
    String? userId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            updates,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> updateProfile({
    required String? userId,
    String? displayName,
    String? avatar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #avatar: avatar,
          },
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<_i5.UserProgress> getUserProgress(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserProgress,
          [userId],
        ),
        returnValue: _i4.Future<_i5.UserProgress>.value(_FakeUserProgress_2(
          this,
          Invocation.method(
            #getUserProgress,
            [userId],
          ),
        )),
      ) as _i4.Future<_i5.UserProgress>);
  @override
  _i4.Future<Map<String, dynamic>> syncOfflineGame(
    String? userId,
    _i5.OfflineGameData? gameData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncOfflineGame,
          [
            userId,
            gameData,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> syncUserProgress(
    String? userId,
    _i5.UserProgress? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncUserProgress,
          [
            userId,
            progress,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> batchSyncGames(
    String? userId,
    List<_i5.OfflineGameData>? games,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchSyncGames,
          [
            userId,
            games,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<void> trackEvent(
    String? eventName,
    Map<String, dynamic>? properties,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEvent,
          [
            eventName,
            properties,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<String> getABTestVariant(String? testName) => (super.noSuchMethod(
        Invocation.method(
          #getABTestVariant,
          [testName],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<void> registerPushToken(
    String? token,
    String? platform,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerPushToken,
          [
            token,
            platform,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<List<Map<String, dynamic>>> getNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue:
            _i4.Future<List<Map<String, dynamic>>>.value(<Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
  @override
  _i4.Future<Map<String, dynamic>> get(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            body,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

class _FakeGameLobby_1 extends _i1.SmartFake implements _i5.GameLobby {
  _FakeGameLobby_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProgress_2 extends _i1.SmartFake implements _i5.UserProgress {
  _FakeUserProgress_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
